### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by hhxmn** [LiuAoyu1998/STIDGCN#7]
Hello author, I am considering quoting your article now. Could you please send me a copy of the processed data sets about PEMS03, PEMS04 and PEMS07? 
Email: hhx_1220@163.com

**Comment by LiuAoyu1998** [comment]
Hello, we have provided processed data at this [link](https://drive.google.com/drive/folders/1-5hKD4hKd0eRdagm4MBW1g5kjH5qgmHR). Due to the large size of the processed dataset, we are unable to email it to you.
![image](https://github.com/LiuAoyu1998/STIDGCN/assets/102887543/a74ba8fb-8941-442d-a4f3-1cde68b15ff0)
